% % FUNÇÃO DO TOOLBOX DE PROCESSAMENTO DIGITAL DE IMAGENS. ESSA FUNÇÃO
% % APLICA UMA EQUALIZAÇÃO O HISTOGRAMA DA IMAGEM DE TAL FORMA QUE TODA A SUA
% % RESOLUÇÃO SEJA APROVEITADA (VALORES ENTRE 0 E 255)...ESSA FUNÇÃO RECEBE
% % COMO PARAMETRO A IMAGEM A SER EQUALIZADA E RETORNA A IMAGEM DEPOIS DE
% % APLICADO O PROCESSO DE EQUALIZAÇÃO, O TAMANHO DA IMAGEM RETORNADA E O
% % MESMO DA IMAGEM ORIGINAL
% % GUILHERME CARVALHO PEREIRA
%% INICIO
function Nimg = myequal(img)        %%CABEÇALHO DA FUNÇÃO
close all;                          %%FECHA TODAS AS JANELAS
clc;                                %%LIMPA O PROMPT DE COMANDO
%% DEFINDO AS DIMENSÕES DA IMAGEM DE SAIDA..SÃO AS MESMAS DA IMAGEM ORIGINAL
[lin , col] = size(img);
sizeImg = lin*col;      %%QUANTIDADE TOTAL DE PIXELS DA IMAGEM
%% APLICANDO A EQUALIZAÇÃO NO HISTOGRAMA
hist = imhist(img) / sizeImg;       %%NORMALIZA O HISTOGRAMA
histAcum = cumsum (hist);
Nimg = histAcum(img+1);
Nimg = uint8(Nimg*255);
end
%% FIM