% % FUNÇÃO DO TOOLBOX DE PROCESSAMENTO DIGITAL DE IMAGENS. ESSA FUNÇÃO APLICA
% % UMA TRANSFORMAÇÃO RADIOMETRICA DE LIMIRIAZAÇÃO (VALORES MAIORES OU
% % IGUAL AO LIMIAR SÃO REPRESENTADOS, OS DEMAIS SÃO 0). A FUNÇÃO RECEBE COMO
% % PARAMETROS UMA IMAGEM E O VALOR DO LIMIAR. ESSA FUNÇÃO RETORNA A IMAGEM
% % DEPOIS DE APLICADA A LIMIARIZAÇÃO, AS IMAGEM TEM O MESMO TAMANHO
% % GUILHERME CARVALHO PEREIRA
%% INICIO
function Nimg = mylimiar_Fundo(img,k)       %%CABEÇALHO DA FUNÇÃO
close all;                              
clc;
%% DEFININDO O TAMNHO DA MATRIZ DE SAIDA..SERÁ O MESMO DA ENTRADA
[lin , col] = size (img);
Nimg = zeros(lin,col);
%% VALORES MAIORES OU IGUAL AO LIMIAR SÃO REPRESENTADOS OS DEMAIS SÃO 0
ind = img >= k;
Nimg(ind) = img(ind);