% % % PROGRAMA 1
% % % PROGRAMA QUE MANIPULA A IMGAEM TREES.TIFF DOS ARQUIVIOS DO MATLAB E APLICA O MAPA DE CORES A ESTA IMAGEM
% % % GUILHERME CARVALHO
%%INICIO
%%LIMPANDO O PROMPT AS VERIÁVEIS E FECHANDO AS JANELAS
clc;
clear all;
close all;
%%LENDO AS IMGAGENS....OBS.: IMAGENS SÃO MATRIZES
A = imread('trees.tif');
[A, map] = imread('trees.tif');         %%APLICANDO O MAPA DE CORES NA IMAGEM
%%MOSTRABDO AS IMAGENS NA TELA
imshow(A)                               %%MOSTRANDO A IMAGEM EM TONS DE CINZA
figure;
imshow(A, map)                          %%MOSTRANDO A IMAGEM COM AS CORES APLICADAS
%%FIM