% % PROGRAMA 3
% % PROGRAMA DESENVOLVIDO PARA EXEMPLIFICAR A CRIA;'AO E ALGUMAS OPERA;'OES COM IMAGENS BINARIA
% % GUILHERME CARVALHO
% % INICIO
%LIMPANDO O PROMPT AS VARIÁVEIS E FECHANDO AS JANELAS
clc;
clear all;
close all;
%CRIANDO AS IMAGENS
BW1 = zeros(20 , 20);                   %%GERA UMA MATRIZ 20X20 COM TODAS AS POSIÇÕES 0
BW1(2:2:18,2:2:18) = 1;                 %%ATRIBUI 1 AS POSIÇÕES QUE TEM LINHA PAR E COLUNA PAR
BW2 = uint8(BW1);                       %%CONVERTE BW1 PARA UNSIGNED 8-bit INTEGER (UINT8)..VALORE VARIAM DE 0 -> 255
BW3 = ~BW2;                             %%BW3 É I INVERSO DE BW2
%MOSTRANDO AS IMAGENS
imshow(BW1)
figure();imshow(BW2)
figure();imshow(BW3)
%%FIM